heat_template_version: 2016-04-08
description: Updated template 4 with updated size of volume. 

resources:
    new_floating_ip:
        type: OS::Neutron::FloatingIP
        properties:
            floating_network: net04_ext
    bootable_volume:
        type: OS::Cinder::Volume
        properties:
            size: 20
            image: Ubuntu-16.04-Xenial-x64-2017-03
    nova_server:
        type: OS::Nova::Server
        properties:
            flavor: p4-3gb
            key_name: default_key_pair
            networks:
                - network: c3tp-collab_network
            block_device_mapping_v2:
                - device_name: vda
                  volume_id: {get_resource: bootable_volume}
                  delete_on_termination: false
    ip_association:
        type: OS::Nova::FloatingIPAssociation
        properties:
            floating_ip: { get_resource: new_floating_ip}
            server_id: {get_resource: nova_server}

